version: '3.3'
services:

  kafka:   
    image: 'spotify/kafka'
    container_name: 'kafka'
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
    network_mode: host
     
  frontend:
    container_name: 'vector-frontend'
    build: './FrontEnd'
    depends_on:
      - kafka
    network_mode: host
   
  backend1:
    container_name: 'vector-backend1'
    build: './Backend1'
    depends_on:
      - kafka
    network_mode: host
   
  backend2:
    container_name: 'vector-backend2'
    build: './Backend2'    
    depends_on:
      - kafka
    network_mode: host
   
